### ISSUE TITLE
Practica- Conexión de Visual Studio con MSQL

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/conexion-bases-de-datos-topicosavanzados-ide#1]
[Practica_conexionBdd_Visual.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-topicosavanzados-ide/files/8666766/Practica_conexionBdd_Visual.pdf)

**Comment by EvelynLopezz** [comment]
PORTADA: 25%
PROCEDIMIENTO: 25%
LISTA DE FIGURAS: 17%
CONCLUSION: 25%
**CALIFICACION IRVING FERNANDO 18.4%**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
