### ISSUE TITLE
Practica_Conexion con MySql

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/conexion-bases-de-datos-topicosavanzados-ide#2]
[Practica_conexion.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-topicosavanzados-ide/files/8673604/Practica_conexion.pdf)

**Comment by EvelynLopezz** [comment]
PORTADA: 25%
PROCEDIMIENTO: 25%
LISTA DE FIGURAS: 17%
CONCLUSION: 25%
**CALIFICACION EDWIN ORTIZ 18.4%**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
