### ISSUE TITLE
Practica2-ConexionDBmySql- DiegoAlexisCarlosCruz 

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/conexion-bases-de-datos-topicosavanzados-ide#3]
[Practica_conexionBdd_Visual.pdf](https://github.com/SistemasTecTlaxiaco/conexion-bases-de-datos-topicosavanzados-ide/files/8723306/Practica_conexionBdd_Visual.pdf)

**Comment by EvelynLopezz** [comment]
PORTADA: 25%
PROCEDIMIENTO: 25%
LISTA DE FIGURAS: 17%
CONCLUSION: 25%
**CALIFICACION DIEGO ALEXIS 18.4%**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
